version: "3"

networks:
  speed:

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    networks:
      - speed
    ports:
      - 3000:3000
    volumes:
      - grafana:/var/lib/grafana

  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    restart: always
    networks:
      - speed
    volumes:
      - influxdb:/var/lib/influxdb
    ports:
      - 8083:8083
      - 8086:8086
    environment:
      - INFLUXDB_ADMIN_USER="admin"
      - INFLUXDB_ADMIN_PASSWORD="password"
      - INFLUXDB_DB="speedtest"
      

  speedtest:
    image: keithdw/speedtest:latest
    container_name: speedtest
    restart: always
    networks:
      - speed
    environment:
      - LOOP=true
      - LOOP_DELAY=600
      - DB_SAVE=true
      - DB_HOST=http://influxdb:8086
      - DB_NAME=speedtest
      - DB_USERNAME=admin
      - DB_PASSWORD=password

volumes:
  grafana:
  influxdb:
